### ISSUE TITLE
No link for project

### ISSUE THREAD

**Issue by kevinwilde** [cschen13/spotitube#1]
I don't see a link anywhere in the repo that would allow me to point my browser to spotitube

**Comment by cschen13** [comment]
Hi, kevinwilde, thanks for checking out my repo. The app is now deployed to Heroku: https://pacific-ravine-30937.herokuapp.com/

Future deployments will also go there until further notice.

Functionality is limited at the moment, but you should be able to retrieve and view your Spotify playlists.
